### ISSUE TITLE
Lack of httpd.conf and tunings of MPM module

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/s2i-base#69]
Not 100% if this issue should be in this repo or somewhere else, so if it is not in the correct area please feel free to tell me to move it. I am doing some performance testing and apache is eating up available memory on my test systems. I went to search for what the default mpm module is set to be used but could not find anything, presuming mpm_prefork. However, I could not find any mention plus there seems to be no specified tunings of apache and said mpm module. E.g.
`<IfModule mpm_prefork_module>
    StartServers           60
    MinSpareServers        20
    MaxSpareServers        100
    ServerLimit            400
    MaxRequestWorkers      300
    MaxConnectionsPerChild 1000
</IfModule>`
I think this is super important to have since it drastically affects the resource utilization of a limits enforced POD.

**Comment by ebalsumgo** [comment]
As an example in v2 you guys have the following mpm_prefork defaults:
`<IfModule prefork.c>
StartServers	   8
MinSpareServers    5
MaxSpareServers   20
ServerLimit	 256
MaxClients	 256
MaxRequestsPerChild  4000
</IfModule>`

Whereas in the sti image all that gets pulled in is 
`# prefork MPM: Implements a non-threaded, pre-forking web server
# See: http://httpd.apache.org/docs/2.4/mod/prefork.html
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so`

Without setting any sorts of resource defaults

**Comment by bparees** [comment]
Thanks for the analysis, can you move this issue to our sti-php repository?

Ben Parees | OpenShift

**Comment by ebalsumgo** [comment]
The problem though is that this is not -php problem but w general problem that all sti-* images I herit, as none of them set their own worker settings but rely on the scl httpd defaults, which there are none set! Which in turn makes httpd extremely inefficient. Mpm_prefork/worker are not tied to a a language, php, perl, ruby, Python... They all end up using httpd as the content provider or the content proxy and the httpd process itself is not tuned when those parameters have no defaults set.


-B

-- Please excuse spelling and grammar errors, this has been sent from my iPhone/iPad

**Comment by mfojtik** [comment]
@remicollet

**Comment by mfojtik** [comment]
@ebalsumgo @bparees we discussed this on scrum today and we come with at least three options:

1) You can rebuild the sti-php image and include your own custom httpd configuration file 
2) If we wait for latest Docker, we can make more clever decisions about what values we set there as we will have access to cgroups and see the CPU/memory/etc which are set for the container
3) We support `.sti/etc/httpd.conf` as part of the assemble and if you have that file in your source code repository, we will copy this file into the httpd config path and make apache pick it up for you. 

Long term we want to have some base httpd image we can layer perl, php and mod_wsgi/python on top which should also use some pluggable configuration mechanism (sti-httpd will just run plain httpd, sti-php will base on sti-httpd and it will just install php rpms and php httpd configuration).

@csrwng CC

**Comment by ebalsumgo** [comment]
To me option 3 is the "best" as at least will allow an easier tuning of Apache if so desired. I discussed this at some leng with cewong on irc, but it def makes sense to have the images come with some "sane" httpd defaults for the process, prefork and worker depending on the content being served. 

The only reason I stumbled onto this is because v3 php with 3 pods could not keep up with traffic for a v2 scaled php gear (up to 3). V3 as it stands right now gets hindered due to httpd getting kernel oom killed.

**Comment by bparees** [comment]
Doing 3 for now and 2 later, ultimately combined with doing that in an
httpd base image instead of in each language image sounds good to me.

But I don't like putting it under a ".sti" path. It's not a file consumed
by sti. For other builders that consume config (eg wildfly) we let users
put a config.xml in a config dir in their source repo, not under the .sti
path, i'd prefer to do the same here.


Ben Parees | OpenShift

**Comment by bparees** [comment]
on a related topic, here's our card for moving to a shared httpd base image:
https://trello.com/c/keOtxxXt/697-add-httpd-s2i-image-as-a-base-for-httpd-images

**Comment by ebalsumgo** [comment]
Has there been any movement on this in any form? I just did a quick test and looked around and it seems the sti images are still based on the same defaults and could not find any documentation on how to overwrite the default httpd.conf (if thats possible yet)

**Comment by bparees** [comment]
no there has not.  today you'd still have to build your own image/layer on top of ours to customize this.

a PR to our assemble scripts (for each s2i image) to allow users to supply their own httpd.conf file in their source repo would be welcome.

**Comment by notroj** [comment]
@hanzz Added support for s2i for our internal RHSCL httpd24 image, I don't think the sources for those changes are pushed to github anywhere yet.

**Comment by mfojtik** [comment]
@ebalsumgo see https://github.com/openshift/s2i-php/issues/96 -> is there anything else you want to tune? Also note that you can now drop any file into /opt/app-root/etc/conf.d and override all httpd settings.

**Comment by ebalsumgo** [comment]
Yeah a few more. As of right now if I am reading the PR correctly there is only support for mpm_prefork (https://httpd.apache.org/docs/2.4/mod/prefork.html) which has a few more options. Then there is mpm_worker (https://httpd.apache.org/docs/2.4/mod/worker.html) as far as I can tell you do not have a way to switch the mpm modules at the moment, but using worker over prefork for non php based images introduces quote a performance bump so it is useful to have the ability to change the mpm module.

Though I guess being able to drop your own httpd.conf file will overwrite the above concerns :)

**Comment by mfojtik** [comment]
@ebalsumgo you will be able to drop custom httpd config file into /opt/app-root/etc/conf.d and we can consider `mpm_worker` for non-php images (just perl AFAIK).

**Comment by ebalsumgo** [comment]
@mfojtik i have not looked at how the tomcat images are setup but if they are apache proxying, mpm_worker works magic with those :). Cool though, being able to tune it in any capacity works with me!

**Comment by ebalsumgo** [comment]
What is the likely hood of these being included in 3.2 or at least 3.2.1?


-B

-- Please excuse spelling and grammar errors, this has been sent from my iPhone/iPad

**Comment by bparees** [comment]
@ebalsumgo 3.2 is unlikely, 3.2.1 is possible, but you can also always use the centos images which are updated immediately, in the meantime.
