### ISSUE TITLE
Use centos:7 instead of centos:centos7

### ISSUE THREAD

**Issue by mfojtik** [openshift/s2i-base#78]
According to centos dockerhub:

```
Rolling builds
The CentOS Project offers regularly updated images for all active releases. These images will be
updated monthly or as needed for emergency fixes. These rolling updates are tagged with the major
version number only. For example: docker pull centos:6 or docker pull centos:7
```

The version we use now is the "released" but not regularly updated one. 
More details: https://hub.docker.com/_/centos/

**Comment by mfojtik** [comment]
@bparees what do you think?

**Comment by bparees** [comment]
"sure, why not?" :)

**Comment by mfojtik** [comment]
origin-base use centos:centos7 @smarterclayton, do you know why?

**Comment by mfojtik** [comment]
@smarterclayton bump? :)

**Comment by smarterclayton** [comment]
Historical, I don't think centos:7 used to exist.

**Comment by bparees** [comment]
@mfojtik make it so.

**Comment by ibotty** [comment]
bump?

**Comment by bparees** [comment]
fixing https://github.com/openshift/s2i-base/pull/103
