### ISSUE TITLE
Error reading passwd file, no such user

### ISSUE THREAD

**Issue by ryanj** [openshift/s2i-base#91]
`npm install bower` is failing with:

    fatal: unable to look up current user in the passwd file: no such user

I think this is due to our randomization of the runtime UID.  Should we add something to the passwd file to ensure this dependency expectation will be fulfillable?

**Comment by bparees** [comment]
I think we just need to do the same nss trick we do in many of our other images:

https://github.com/openshift/s2i-python/blob/master/3.3/s2i/bin/run#L2
https://github.com/openshift/s2i-python/blob/master/3.3/contrib/etc/generate_container_user

(except we need to execute that logic in the assemble script in this case)

**Comment by ryanj** [comment]
crap - I'm having trouble reproducing this issue, now that I'm going back to validate the fix.

**Comment by GrahamDumpleton** [comment]
I can't see how this would be needed in the assemble script as it should be running as the ``USER`` 1001 specified by the image and that should be mapping to ``default`` user. If ``npm install`` is being run somehow by application when final container is being run, that is different matter and could be a problem.

**Comment by bparees** [comment]
@GrahamDumpleton is right, in my PR i didn't need to include the nss logic in the assemble script.  I don't think it hurts, but it isn't needed, and therefore `npm install bower` should also work fine if it's being run in assemble.  (if it's being run in the "run" script then that's another story... perhaps that's how you hit the original issue @ryanj ?  were you doing the `npm install bower` in the run script?)

**Comment by ryanj** [comment]
I originally hit the issue while running `npm install` in a web console terminal.  I haven't seen the it come up recently.

**Comment by bparees** [comment]
that would also make sense, but i don't think my pull would address that case either, as @GrahamDumpleton noted.
