### ISSUE TITLE
Define how image streams are created from openshift/s2i-*

### ISSUE THREAD

**Issue by sdodson** [openshift/s2i-base#95]
Currently, we've got some images that lack image stream definitions in https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json and https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json namely NodeJS 4.

I'd like to propose that as part of the image definition in the openshift/s2i-* and sclorg/s2i-* repos we maintain the image streams there rather than in the origin repo so that they can, and ideally must, be created at the same time that the Dockerfiles are created here.

@bparees @hhorak thoughts?

**Comment by sdodson** [comment]
CC: @sferich888

**Comment by bparees** [comment]
we're just going to keep updating the imagestream file as we approve/ship/support new image versions:
https://trello.com/c/JOT2Z2un/946-1-prepare-and-execute-test-cases-to-certify-the-new-scl-2-2-images
https://trello.com/c/8qt2hCOE/945-update-imagestreams-for-scl-2-2
https://github.com/openshift/origin/pull/9157

**Comment by sdodson** [comment]
That's fine, when I filed this I was under the impression that the nodejs 4 image was officially supported, but i was misinformed.
